name: "Exercicio 2"

on: push
  
jobs:
  cria_e_upload_artefatos:
    name: "Cria artefato e faz upload"
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3
