name: "Hello world workflow"

on:
  push:
  
jobs:
  print_hello_world_ubuntu:
    name: Hello world Ubuntu!
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello world Ubuntu!
        run: |
          echo 'Date Ubuntu'
          date
        
  print_hello_world_windows:
    name: Hello world Windows!
    runs-on: windows-latest
    
    steps:
      - name: Hello world Windows!
        run: |
          echo 'Date Windows'
          date
        
  print_hello_world_macos:
    name: Hello world MacOS!
    runs-on: macos-latest
    
    steps:
      - name: Hello world MacOS!
        run: |
          echo 'Date MacOS'
          date
        
  
  print_hello_world_ubuntu2:
    name: Hello world Ubuntu2!
    runs-on: ubuntu-latest
    needs:
      - print_hello_world_ubuntu
      - print_hello_world_windows
      - print_hello_world_macos
    
    steps:
      - name: Hello world Ubuntu2!
        run: |
          echo 'Date Ubuntu2'
          date
