name: "Exercicio 1"

on:
  push:
  
jobs:
  print_ubuntu:
    name: Date Ubuntu!
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Ubuntu!
        run: |
          echo 'Date Ubuntu'
          date
        
  print_windows:
    name: Date Windows!
    runs-on: windows-latest
    
    steps:
      - name: Print Windows!
        run: |
          echo 'Date Windows'
          date
        
  print_macos:
    name: Date MacOS!
    runs-on: macos-latest
    
    steps:
      - name: Print MacOS!
        run: |
          echo 'Date MacOS'
          date
        
  
  print_ubuntu2:
    name: Print Ubuntu2!
    runs-on: ubuntu-latest
    needs:
      - print_ubuntu
      - print_windows
      - print_macos
    
    steps:
      - name: Print Ubuntu2!
        run: |
          echo 'Date Ubuntu2'
          date
